# Generated by Django 4.2.11 on 2026-07-05 10:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coop_name', models.CharField(default='Chrisland University Cooperative', max_length=200)),
                ('coop_reg_number', models.CharField(blank=True, max_length=50)),
                ('coop_address', models.TextField(blank=True)),
                ('coop_phone', models.CharField(blank=True, max_length=15)),
                ('coop_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='coop/')),
                ('monthly_contribution_amount', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('max_loan_multiplier', models.FloatField(default=3.0, help_text='Maximum loan = savings × multiplier')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('late_payment_penalty_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('min_savings_for_loan', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('min_months_for_loan', models.IntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cooperative Settings',
                'verbose_name_plural': 'Cooperative Settings',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)])),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Annual interest rate (%)', max_digits=5)),
                ('tenure_months', models.IntegerField(help_text='Loan duration in months', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('purpose', models.CharField(choices=[('business', 'Business Expansion'), ('education', 'Education / School Fees'), ('medical', 'Medical Expenses'), ('housing', 'Housing / Renovation'), ('agriculture', 'Agriculture'), ('personal', 'Personal / Emergency'), ('other', 'Other')], default='personal', max_length=20)),
                ('purpose_description', models.TextField(blank=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=100)),
                ('guarantor_phone', models.CharField(blank=True, max_length=15)),
                ('guarantor_member_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active / Disbursed'), ('overdue', 'Overdue'), ('repaid', 'Fully Repaid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('risk_score', models.CharField(blank=True, choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=10)),
                ('risk_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(choices=[('civil_servant', 'Civil Servant'), ('private', 'Private Sector'), ('self_employed', 'Self Employed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], default='other', max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('next_of_kin', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=25, unique=True)),
                ('transaction_type', models.CharField(choices=[('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('contribution', 'Contribution'), ('penalty', 'Penalty Fee'), ('dividend', 'Dividend')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='Loan ID / Savings ID etc', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cooperative.member')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('dividend', 'Dividend Credit')], default='deposit', max_length=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_records', to='cooperative.member')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Record',
                'verbose_name_plural': 'Savings Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('installment_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='confirmed', max_length=10)),
                ('is_late', models.BooleanField(default=False)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, default='Cash', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='cooperative.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_due', 'Loan Due Reminder'), ('repayment_confirmed', 'Repayment Confirmed'), ('savings_credited', 'Savings Credited'), ('contribution_due', 'Contribution Due'), ('general', 'General Announcement'), ('risk_alert', 'Risk Alert')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('risk_level', models.CharField(choices=[('Low', 'Low Risk'), ('Medium', 'Medium Risk'), ('High', 'High Risk')], max_length=10)),
                ('default_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('algorithm_used', models.CharField(choices=[('random_forest', 'Random Forest'), ('logistic_regression', 'Logistic Regression'), ('decision_tree', 'Decision Tree')], default='random_forest', max_length=25)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('months_as_member', models.IntegerField(default=0)),
                ('previous_defaults', models.IntegerField(default=0)),
                ('contribution_consistency', models.FloatField(default=0)),
                ('debt_to_savings_ratio', models.FloatField(default=0)),
                ('repayment_history_score', models.FloatField(default=0)),
                ('feature_importances', models.JSONField(blank=True, null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='cooperative.member')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_set', to='cooperative.member'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('special', 'Special Levy')], default='monthly', max_length=15)),
                ('period', models.CharField(help_text='e.g. May 2025', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_paid', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='cooperative.member')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
