# Generated by Django 4.2.11 on 2026-07-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paystack_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('contribution', 'Contribution'), ('penalty', 'Penalty Fee'), ('dividend', 'Dividend'), ('bank_deposit', 'Bank Deposit'), ('bank_withdrawal', 'Bank Withdrawal')], max_length=25),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(help_text='Name returned by Paystack account resolution', max_length=150)),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Used for withdrawals via Paystack Transfers', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='cooperative.member')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('member', 'account_number', 'bank_code')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cooperative.bankaccount'),
        ),
    ]
