# Generated by Django 4.2.11 on 2026-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_transaction_paystack_reference_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO code, e.g. USD, GBP, EUR', max_length=3, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
                ('rate_to_ngn', models.DecimalField(decimal_places=4, help_text='1 unit of this currency = this many Naira', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency_code'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in `currency` before conversion to Naira', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency the member entered', max_length=3),
        ),
    ]
