# Generated by Django 4.2.11 on 2026-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_exchangerate_transaction_amount_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Administrator'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('auditor', 'Auditor')], default='member', help_text='Governs which admin actions are permitted (only relevant when is_admin=True)', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Grants access to the admin panel'),
        ),
    ]
