# Generated by Django 4.2.11 on 2026-07-12 12:01

import cooperative.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_member_role_alter_member_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='coop/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), cooperative.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), cooperative.models.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='cooperative_status_a3bd57_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'status'], name='cooperative_member__50519f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='cooperative_status_528461_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['role'], name='cooperative_role_5daffe_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='cooperative_recipie_98fe6b_idx'),
        ),
        migrations.AddIndex(
            model_name='savings',
            index=models.Index(fields=['member', 'date'], name='cooperative_member__cf4a67_idx'),
        ),
        migrations.AddIndex(
            model_name='savings',
            index=models.Index(fields=['transaction_type'], name='cooperative_transac_7651d1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['member', 'date'], name='cooperative_member__726f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='cooperative_transac_3a06ae_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='cooperative_status_3a77e8_idx'),
        ),
    ]
