# Generated by Django 4.2.11 on 2026-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0005_alter_coopsettings_logo_alter_member_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopsettings',
            name='coop_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
